dependencies:
- python=3.8.*
- ipywidgets==7.5.1
  #- jupyterlab==2.2.0
  #- jupyterhub-singleuser==1.1.0
- nbconvert==5.6.1
- nbresuse==0.3.3
- notebook==6.0.3
- nbgitpuller==0.9.0
  #- nteract_on_jupyter==2.1.3
